# Generated by Django 4.2.7 on 2024-01-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='some_default_image.jpg', upload_to='covers/'),
            preserve_default=False,
        ),
    ]
