# Generated by Django 4.2.7 on 2024-01-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review_comment_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FICTION', 'Fiction'), ('NON-FICTION', 'Non-Fiction'), ('AUTOBIOGRAPHY', 'Autobiography'), ('NOVELS', 'Novels'), ('THRILLERS', 'Thrillers'), ('HISTORY', 'History'), ('POETRY', 'Poetry')], max_length=20)),
            ],
        ),
    ]
